version: "3.9"
services:
  wed:
    container_name: react-docker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
